config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } 
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'favicon.ico', to: proc { [204, {}, ['']] }
  get 'homes/about'
  get 'homes/chatbot'

  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  patch 'users/withdraw' => 'users#withdraw'
  
  get 'searches/search'
  get '/post/hashtag/:name', to: "posts#hashtag"
  
  post "/chatbots", to: "chatbots#create"
  
  
  resources :users, only:[:show, :edit, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get :favorites, on: :collection
    member do
      patch 'nonrelease'
      patch 'release'
    end
  end
  
  
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
    post 'teachme'
    end
  end
  
  resources :rooms, only: [:show]
  resources :chats, only: [:show, :create]

  resources :group_rooms, only: [:index, :new, :create, :show, :edit, :update, :destroy] 

  post 'group_rooms/:id', to: 'group_rooms#groupchat', as: 'group_chats'
  
  resources :notifications, only: [:index, :destroy]
  
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  has_one :notification, as: :subject, dependent: :destroy
  validates_uniqueness_of :follower_id, scope: :followed_id
  after_create_commit :create_notifications
  

  private
  
  def create_notifications
    Notification.create(subject: self, user: followed, action_type: :followed_me)
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 before_action :authenticate_user!
 before_action :ensure_guest_user, only: [:create, :destroy, :followings, :followers]
 
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
		redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
		redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
		@users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
		@users = user.followers
  end
  
  private
  
  def ensure_guest_user
    if current_user.email == "guest@example.com"
      redirect_to root_path , notice: "ゲストユーザーはこの機能はご使用いただけません。"
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "unfollow", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-info" %>
  <% else %>
    <%= link_to "follow", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      <h5>Followers List  〈 <%= @users.count %> 〉</h5><br/>
        <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-4 mb-3">
            <%= image_tag user.get_icon_image(100,100), class: "icon" %>
            <br>
            <%= user.user_name %>
            <br>
            <%= link_to "Look", user_path(user.id), class: "button-14", role: "button", style: "margin-top: 2px;" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      <h5>Followings List  〈 <%= @users.count %> 〉</h5><br/>
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-4 mb-3">
            <%= image_tag user.get_icon_image(100,100), class: "icon" %>
            <br>
            <%= user.user_name %>
            <br>
            <%= link_to "Look", user_path(user.id), class: "button-14", role: "button", style: "margin-top: 2px;" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>