config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } 
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'favicon.ico', to: proc { [204, {}, ['']] }
  get 'homes/about'
  get 'homes/chatbot'

  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  patch 'users/withdraw' => 'users#withdraw'
  
  get 'searches/search'
  get '/post/hashtag/:name', to: "posts#hashtag"
  
  post "/chatbots", to: "chatbots#create"
  
  
  resources :users, only:[:show, :edit, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get :favorites, on: :collection
    member do
      patch 'nonrelease'
      patch 'release'
    end
  end
  
  
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
    post 'teachme'
    end
  end
  
  resources :rooms, only: [:show]
  resources :chats, only: [:show, :create]

  resources :group_rooms, only: [:index, :new, :create, :show, :edit, :update, :destroy] 

  post 'group_rooms/:id', to: 'group_rooms#groupchat', as: 'group_chats'
  
  resources :notifications, only: [:index, :destroy]
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # フォローをした、されたの関係
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :group_entries, dependent: :destroy
  has_many :group_chats, dependent: :destroy
  has_many :group_rooms, through: :group_entries, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  has_one_attached :icon_image
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name ="ログイン"
      user.user_name ="guest"
      user.telephone_number ="090000000000"
    end
  end
  
  def guest?
    user_name =="guest"
  end
  
  def get_icon_image(width, height)
    unless icon_image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpg')
      icon_image.attach(io: File.open(file_path), filename: 'NoImage.jpg', content_type: 'image/jpg')
    end
      icon_image.variant(resize_to_limit: [width, height]).processed
  end
  
    # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  
  # ユーザーが特定のユーザーにフォローされているかどうかを確認するメソッド
  def followed_by?(other_user)
    other_user.following?(self)
  end
  
  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
    if mutual_followings.map(&:id).include?(user.id)
       Room.find_or_create_by(user_id: user.id) do |room|
         room.user_id = user.id
       end
    end
  end
  
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    relationship = active_relationships.find_by(followed_id: user.id)
    if relationship.present?
       relationship.destroy
    end
  end
  
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
  
  # 相互フォロー一覧を取得
  def mutual_followings
    following_users = self.followings
    followers_users = self.followers
    mutual_followings = following_users & followers_users
    mutual_followings
  end
  
  # 検索方法分岐
  def self.search(search, word)
    if search == "perfect_match"
      where("user_name LIKE ?", word)
    elsif search == "forward_match"
      where("user_name LIKE ?", "#{word}%")
    elsif search == "backward_match"
      where("user_name LIKE ?", "%#{word}")
    elsif search == "partial_match"
      where("user_name LIKE ?", "%#{word}%")
    else
      all
    end
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      where("user_name LIKE ?", "#{word}")
    elsif search == "forward_match"
      where("user_name LIKE ?", "#{word}%")
    elsif search == "backward_match"
      where("user_name LIKE ?", "%#{word}")
    elsif search == "partial_match"
      where("user_name LIKE ?", "%#{word}%")
    else
      all
    end
  end
  # 公開非公開のステータス
  enum status:{nonreleased: 0, released: 1}
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create
  
  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :ensure_normal_user, only: %i[update destroy]
  
  def ensure_normal_user
    if resource.email == 'guest@example.com'
       redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :icon_image, :user_name, :telephone_number])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]
  
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  protected

  def user_state
    ## 【処理内容1】 入力されたemailからアカウントを1件取得
    @user = user.find_by(email: params[:user][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@user
    ## 【処理内容2】 メールがあり、取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @user.valid_password?(params[:user][:password])
      ## 【処理内容3】もしパスワードが一致していて、削除されたアカウントの場合
      if @user.is_deleted
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください"
        redirect_to new_user_registration_path
      end
      ## 【処理内容3】もしパスワードが有効でも削除されていなかったら...何も書く必要はない。
    end
  end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :set_user, only: [:followings, :followers]

  def show
    @user=User.find(params[:id])
    @posts = @user.posts.order('id DESC')
    
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)  
    @favorite_list = Post.find(favorites) 
    
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    
    unless @user.id == current_user.id
           @current_entry.each do |current|
             
             @another_entry.each do |another|
              if current.room_id == another.room_id
                   @is_room = true
                   @room_id = current.room_id
              end
             end
             
           end
           
    unless @is_room
           @room = Room.new
           @entry = Entry.new
    end
    end
  end
  

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    
    if @user.update(user_params)
       flash[:notice] = "変更を保存しました"
       redirect_to user_path(current_user.id)
    else
       render :edit
    end
  end

  def confirm_withdraw
  end

  def withdraw
    @user = current_user
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    #セッション情報を全て削除
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    #退会後トップ画面に遷移
    redirect_to root_path
  end
  
  def release
    @user =  User.find(params[:id])
    @user.released! unless @user.released?
    redirect_to  "/users/#{@user.id}/edit", notice: 'このアカウントを公開しました'
  end

  def nonrelease
    @user =  User.find(params[:id])
    @user.nonreleased! unless @user.nonreleased?
    redirect_to "/users/#{@user.id}/edit", notice: 'このアカウントを非公開にしました'
  end
  
  def favorites
    @user = current_user
    favorite_posts = @user.favorites.pluck(:post_id)
    @favorite_posts = Post.where(id: favorite_posts)
    @favorite_posts_none = "いいね した投稿がありません。"
  end
  
  
  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end
  

  private
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to root_path, notice: "You cannot move to other people's screens."
    end
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :user_name, :icon_image, :telephone_number, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm_withdraw.html.erb
<div class="container">
  <div class="row m-5 justify-content-center">
    <div class="col text-center">
      <h5>退会のお手続き</h5>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col text-center">
      <p>
        ※ご確認ください
        <br>
        <br>
        アカウントが削除されると、そのアカウントはTeach me!で利用できなくなります。
        <br>
        また、過去のアカウントを復活させたり、以前の投稿にアクセスしたりすることもできなくなります。
        <br>
        <br>
        退会する場合は、「退会する」をクリックしてください。
      </p>
      
      <br>
      <br>
      
      <ul>
        <li><%= link_to '退会しない', user_path(current_user) %></li>
        <li>|</li>
        <li><%= link_to '退会する', users_withdraw_path, method: :patch, data: { confirm: "本当に退会しますか？" } %></li>
      </ul>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      <h1>ユーザー情報編集</h1>
    </div>
  </div>
  <div class="row m-3">
    <div class="col-sm-11 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @user, url: users_information_path(id: @user), method: :patch do |f| %>
        <%= render "devise/shared/error_messages", resource: @user %>

<div class="form-group">
  <label for="name">名前</label>
  <div class="row">
    <div class="col">
      <%= f.text_field :last_name, class: "form-control block", id: "user_last_name" %>
    </div>
    <div class="col">
      <%= f.text_field :first_name, class: "form-control block", id: "user_first_name" %>
    </div>
  </div>
</div>

<div class="form-group">
  <label for="user_name">ユーザーネーム</label>
  <div class="row">
    <div class="col">
      <%= f.text_field :user_name, class: "form-control block", id: "user_name" %>
    </div>
  </div>
</div>

<div class="form-group">
  <label for="icon_image">アイコン</label>
  <div class="row">
    <div class="col">
      <%= f.file_field :icon_image, accept: "image/*", class: "form-control block", id: "icon_image" %>
    </div>
  </div>
</div>

<div class="form-group">
  <label for="telephone_number">電話番号</label>
  <div class="row">
    <div class="col">
      <%= f.text_field :telephone_number, class: "form-control block", id: "telephone_number" %>
    </div>
  </div>
</div>

<div class="form-group">
  <label for="email">メールアドレス</label>
  <div class="row">
    <div class="col">
      <%= f.email_field :email, class: "form-control block", id: "email" %>
    </div>
  </div>
</div>
          
  <div class="row mb-4">
    <div class="col mt-2 mr-1">
      <%= f.submit "編集を保存", class: "button-14", role: "button", style: "margin-top: 2px;" %>
    </div>
    <div class="col mt-2 mr-1">
      <% if @user.released? %>
        <%= link_to '非公開',nonrelease_user_path(@user), method: :patch, class: "link" %>
        <i class="fas fa-lock"></i>
      <% else %>
        <%= link_to '公開',release_user_path(@user), method: :patch, class: "link" %>
        <i class="fas fa-unlock"></i>
      <% end %>
    </div>
    
    <div class="col mt-2 mr-1">
      <%= link_to '退会', users_confirm_withdraw_path, class: "link" %>
    </div>
  </div>
  
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      <h1>Favorite list</h1>
      
      <% if @favorite_posts == [] %>
      <%= @favorite_posts_none %>
      <% end %>
      
      <% if @favorite_posts.present? %>
        <table class="table table-hover table-inverse">
          <tbody>
            <% @favorite_posts.each do |post| %>
            <tr>
              <td><%= link_to post_path(post.id) do %>
                    <%= image_tag post.get_image(300,300) %>
                  <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      
  <div class="row">
    <ul>
      <li>
        <strong>Profile</strong>
        <br>
        <%= image_tag @user.get_icon_image(100,100),class:"icon" %>
      </li>
      <li>
        name：<%= @user.user_name %>
      <br>
        user_id：<%= @user.id %>
      </li>
      <li>
        <% if current_user %>
        <% if current_user.email == 'guest@example.com' && current_user.email == @user.email %>
          <p>※ゲストユーザーはユーザー情報の編集ができません。</p>
          <%= link_to "", favorites_users_path, class: "fas fa-heart" %>
          <%= link_to "", room_path(@user), class: "far fa-comment-dots" %>
          <%= link_to "", new_post_path, class: "fas fa-edit" %>
        <% elsif current_user == @user %>
          <%= link_to "", users_information_edit_path(id: @user), class: "fas fa-cog" %>
          <%= link_to "", favorites_users_path, class: "fas fa-heart" %>
          <%= link_to "", room_path(@user), class: "far fa-comment-dots" %>
          <%= link_to "", new_post_path, class: "fas fa-edit" %>
        <% else %>
          <!-- 他のユーザー向けの表示 -->
        <% end %>
      <% else %>
        <!-- ログインしていないユーザー向けの表示 -->
      <% end %>
      </li>
      <li>
        <%= link_to "follow", user_followings_path(@user), class: "link" %>:<%= @user.followings.count %>
      <br>
        <%= link_to "follower", user_followers_path(@user), class: "link" %>:<%= @user.followers.count %>
      </li>
      <li>
        <%= render "relationships/btn", user: @user, options: { class: "button-14", role: "button", style: "margin-top: 2px;" } %>
      </li>
    
      <li>
        <% if current_user != @user %>
          <%= link_to 'D M', chat_path(@user.id), class: "button-14", role: "button", style: "margin-top: 2px;" %>
        <% end %>
      </li>
    </ul>
  </div>
  
  <div class="row">
    <% @posts.each do |post| %>
      <div>
        <%= link_to post_path(post.id) do %>
          <%= image_tag post.get_image(350,350) %>
        <% end %>
      </div>
    <% end %>
  </div>
  
    </div>
  </div>
</div>