config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } 
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'favicon.ico', to: proc { [204, {}, ['']] }
  get 'homes/about'
  get 'homes/chatbot'

  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  patch 'users/withdraw' => 'users#withdraw'
  
  get 'searches/search'
  get '/post/hashtag/:name', to: "posts#hashtag"
  
  post "/chatbots", to: "chatbots#create"
  
  
  resources :users, only:[:show, :edit, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get :favorites, on: :collection
    member do
      patch 'nonrelease'
      patch 'release'
    end
  end
  
  
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
    post 'teachme'
    end
  end
  
  resources :rooms, only: [:show]
  resources :chats, only: [:show, :create]

  resources :group_rooms, only: [:index, :new, :create, :show, :edit, :update, :destroy] 

  post 'group_rooms/:id', to: 'group_rooms#groupchat', as: 'group_chats'
  
  resources :notifications, only: [:index, :destroy]
  
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = params[:range]
    @users = []
    @posts = []
    @tag = params[:word]
    
    if @range == "User"
       @users = User.looks(params[:search], params[:word]).where.not(status: "nonreleased")
    else
       @posts = Post.where("caption LIKE ?", "%#{params[:word]}%").where.not(user: User.where(status: "nonreleased"))
       # キャプション（caption）が指定のキーワードを含む投稿を検索
    end
  
       # ハッシュタグ検索
    if params[:q].present? && !params[:q].empty?
       # 検索クエリが提供された場合の処理
       @tag = params[:q]
       hashtag = Hashtag.find_by(hashname: params[:q])
       @posts = hashtag ? hashtag.posts : []
    end
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_searchform.html.erb
<div class="search_form">
  <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['Post'], ['User']]) %>
    <%= f.select :search, options_for_select([["All","perfect_match"],["Part","partial_match"]]) %>
    <%= f.submit "検索", class: "button-14", role: "button", style: "margin-top: 2px;" %>
  <% end %>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col">
      <%= render partial: "searchform" %>
      <br>
      <h2>#<%= @tag %></h2>
      <br
      <table class="table table-hover table-inverse">
        <!--検索対象モデルがUserの時 -->
        <% if @range == "User" %>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user.user_name, user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
        <% else %>
        <!--検索対象モデルがUserではない時(= 検索対象モデルがpostの時) -->
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post_path(post.id) do %>
                  <%= image_tag post.get_image(300,300) %>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>