config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } 
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'favicon.ico', to: proc { [204, {}, ['']] }
  get 'homes/about'
  get 'homes/chatbot'

  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  patch 'users/withdraw' => 'users#withdraw'
  
  get 'searches/search'
  get '/post/hashtag/:name', to: "posts#hashtag"
  
  post "/chatbots", to: "chatbots#create"
  
  
  resources :users, only:[:show, :edit, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get :favorites, on: :collection
    member do
      patch 'nonrelease'
      patch 'release'
    end
  end
  
  
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
    post 'teachme'
    end
  end
  
  resources :rooms, only: [:show]
  resources :chats, only: [:show, :create]

  resources :group_rooms, only: [:index, :new, :create, :show, :edit, :update, :destroy] 

  post 'group_rooms/:id', to: 'group_rooms#groupchat', as: 'group_chats'
  
  resources :notifications, only: [:index, :destroy]
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :post_hashtag_relations, dependent: :destroy
  
  has_one_attached :image
  has_one :notification, as: :subject, dependent: :destroy
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpg')
      image.attach(io: File.open(file_path), filename: 'NoImage.jpg', content_type: 'image/jpg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  
    #「ログイン中のユーザーがその投稿に対していいねをしているか」を判断する
  def favorite?(user)
  favorites.where(user_id: user.id).exists?
  end                 #(current_user)のidと等しいuser_idを持つレコードは、favoritesテーブル内に存在するか？」をexists?を用いて判断
                      #一致するレコードが存在しない＝「まだいいねしていない→createアクションへ」
                      #一致するレコードが存在する＝「すでにいいね済み→destroyアクションへ」と分岐
  
  
  # 検索方法分岐
  def self.search(search, word)
    if search == "perfect_match"
      where("caption LIKE ?", word)
    elsif search == "forward_match"
      where("caption LIKE ?", "#{word}%")
    elsif search == "backward_match"
      where("caption LIKE ?", "%#{word}")
    elsif search == "partial_match"
      where("caption LIKE ?", "%#{word}%")
    else
      all
    end
  end
  
  after_create do
    created_post = Post.find_by(id: self.id) # ポストを作成した後、保存されたポストを取得
    hashtags = self.caption.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    created_post.hashtags = []
    hashtags.uniq.map do |hashtag|
    tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
    created_post.hashtags << tag
    end
  end

  before_update do 
    created_post = Post.find_by(id: self.id) # モデル名を指定する
    created_post.hashtags.clear
    hashtags = self.caption.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
      created_post.hashtags << tag
    end
  end
  
  validates :caption, presence: true
  validates :code_url, presence: true
  validates :post_url, presence: true
  validates :image, presence: true
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:new, :edit, :update]
  before_action :set_post, only: [:show, :edit, :update, :teachme, :destroy, :is_matching_login_user]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
       flash[:notice] = "Successfully"
       redirect_to posts_path
    else
       flash.now[:notice] = "Could not post"
       render :new
    end
  end
  
  
  def index
    @posts =  Post.where.not(user: User.where(status: "nonreleased")).order('id DESC')
  end
  

  def show
    @comment = Comment.new
  end
  

  def edit
  end
  
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  
  def update
    if @post.update(post_params)
       flash[:notice] = "Successfully"
       redirect_to post_path(@post.id)
    else
       flash.now[:notice] = "Could not update"
       render :edit
    end
  end
  
  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posts = @tag.posts
  end
  
  
  def teachme
    if @post
      # Teachme カウントを増加
      @post.increment!(:teachmes_count)
    end
      redirect_to @post.code_url
  end
  
  
  private

  def post_params
    params.require(:post).permit(:caption, :image, :post_url, :code_url)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def is_matching_login_user
    unless @post.user_id == current_user.id
           redirect_to root_path, notice: "You cannot move to other people's screens."
    end
  end
  
  def ensure_guest_user
    if current_user.email == "guest@example.com"
       redirect_to root_path , notice: "ゲストユーザーはこの機能はご使用いただけません。"
    end
  end  
  
end

app/helpers/posts_helper.rb
module PostsHelper
  # ハッシュタグ（# または ＃ で始まる単語）をリンクに変換する
  def render_with_hashtags(caption)
      caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) do |word|
      link_to word, "/searches/search?q=#{CGI.escape(word[1..-1])}"
      end.html_safe
  end 
end

app/views/posts/edit.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
    
        
  <div class="row m-3">
    <div class="col-12 px-5 px-sm-0 margin:0 ">
      <h1>Post edit</h1>
      <%= form_with model: @post,url: post_path do |f| %>
  
  <div class="form-group row">
    <label for="inputImage" class="col-sm-2 col-form-label">投稿画像</label>
    <div class="col-sm-10">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>
  
  <div class="form-group row">
    <label for="inputCaption" class="col-sm-2 col-form-label">投稿文</label>
    <div class="col-sm-10">
      <%= f.text_area :caption, placeholder:"文章を記入する際に『＃』を使用すると検索時に検索されやすくなります", class: "w-100", rows: 10 %>
    </div>
  </div>
  
  <div class="form-group row">
    <label for="inputPostUrl" class="col-sm-2 col-form-label">投稿URL</label>
    <div class="w-100 col-sm-10">
      <%= f.text_field :post_url, placeholder:"投稿するWebサービスのURLを記入してください", class: "w-100" %>
    </div>
  </div>
  
  <div class="form-group row">
    <label for="inputCodeUrl" class="col-sm-2 col-form-label">コードURL</label>
    <div class="w-100 col-sm-10">
      <%= f.text_field :code_url, placeholder:"コードのURL（Github等）を記入してください", class: "w-100" %>
    </div>
  </div>
  
  <div class="form-group row text-right">
    <div class="col-sm-10">
      <%= f.submit "変更を保存", class: "button-14", role: "button", style: "margin-top: 2px;" %>
    </div>
  </div>
  
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      <h1>Time line</h1>


  <div class="row">
    <% @posts.each do |post| %>
      <%= link_to post_path(post.id) do %>
      <table>
        <tr>
          <td>
            <%= image_tag post.get_image(350,350) %>
          </td>
        </tr>
      </table>
      <% end %>
    <% end %>
  </div>
  
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col p-3">
      
      <%= image_tag current_user.get_icon_image(100,100),class:"icon" %><br>

      <%= form_with model: @post,url: posts_path do |f| %>
      
  <div class="form-group row">
    <label for="inputImage" class="col-sm-2 col-form-label">投稿画像</label>
    <div class="col-sm-10">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>
  
  <div class="form-group row">
    <label for="inputCaption" class="col-sm-2 col-form-label">投稿文</label>
    <div class="col-sm-10">
      <%= f.text_area :caption, placeholder:"文章を記入する際に『＃』を使用すると検索されやすくなります", class: "w-100", rows: 10 %>
    </div>
  </div>
  
  
  <div class="form-group row">
    <label for="inputPostUrl" class="col-sm-2 col-form-label">投稿URL</label>
    <div class="col-sm-10">
      <%= f.text_field :post_url, placeholder:"投稿するWebサービスのURLを記入してください", class: "w-100" %>
    </div>
  </div>
  
  
  <div class="form-group row">
    <label for="inputCodeUrl" class="col-sm-2 col-form-label">コードURL</label>
    <div class="col-sm-10">
      <%= f.text_field :code_url, placeholder:"コードのURL（Github等）を記入してください", class: "w-100" %>
    </div>
  </div>
  
  
  <div class="form-group row text-right">
    <div class="col-sm-10">
      <%= f.submit "公開する", class: "button-14", role: "button", style: "margin-top: 2px;" %>
    </div>
  </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      
        <%= image_tag @post.user.get_icon_image(100,100),class:"icon" %>
        <%= link_to @post.user.user_name, user_path(@post.user.id) %>
      <div>
        <%= image_tag @post.get_image(550,550) %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="post-details">
      <div class="post-border">
        <p>------------------------------------------------------</p>
      </div>
        <p><%= simple_format(render_with_hashtags(@post.caption)) %></p>
      </div>
      
      <div class="button">
        <% if @post.user == current_user %>
          <div style="display: inline-block; margin-right: 10px;">
            <%= link_to edit_post_path, class: "button-12", role: "button", style: "margin-top: 2px;" do %>
              <span>edit</span>
            <% end %>
            <%= link_to @post, method: :delete, data: { confirm: "本当に消しますか?" }, class: "button-12", role: "button", style: "margin-top: 2px;" do %>
              <span>delete</span>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="post-border">
        <p>------------------------------------------------------</p>
      </div>
      <br>
      <i class="far fa-paper-plane"></i>
      <%= link_to @post.post_url, class: "link" do %>
        <span>Check the Web</span>
      <% end %>
      <br>
      <br>
      <!--SNS連携ボタンの設置-->
      <a class="twitter-share-button" href="https://twitter.com/intent/tweet?url=<%= request.original_url %>&text=Teach%20me!%20%E3%82%B7%E3%82%A7%E3%82%A2">Tweet</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      <div class="line-it-button" data-lang="ja" data-type="share-a" data-env="REAL" data-url="<%= request.original_url %>" data-color="default" data-size="small" data-count="false" data-ver="3" style="display: none;"></div>
      <script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
      
    </div>
  </div>
</div>
      
<div class="container">
  <div class="row">
    <div class="col-md-6">
  
      <div class="post-interactions">
        <div class="button-container">
          <div id="favorite_btn_<%= @post.id %>">
            <%= render "favorites/btn", post: @post %>
          </div>
          <div class="teachme-button">
            <%= link_to teachme_post_path(@post),method: :post, class: "button-8", role: "button" do %>
            <span>Teach me!</span>
            <% end %>
            <i class="fas fa-eye"></i>
            <span class="teachme-count"><%= @post.teachmes_count %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <p id="comment_counter">comment： <%= @post.comments.count %></p>
        <div id="comment_index">
          <%= render "comments/index", post: @post, comment: @comment %>
        </div>
          <%= render "comments/form", post: @post, comment: @comment %>
        
      </div>
    </div>
  </div>
</div>